Backend/authentication
openknowledgebe/open-wallet pull request #2
Opened 2019-03-21 10:12 UTC by auloin

Quite a lot already.
Need a critical look at the folder structures.
Where should I put Business logic (like email validity check)? In the model? A custom middleware in between graphql & mongoose?

2019-03-27 13:16 UTC, MichielLeyman commented on backend/src/graphql/resolvers/queries.js
> +  users: async () => (users = await User.find()),
`users` is undefined. Did you want to return `User.find()`?

2019-03-27 13:17 UTC, MichielLeyman commented on backend/src/graphql/resolvers/mutations.js
> +    // TODO Valid email format
Are you doing validation all at once in a separate PR?
Might be worth doing straight away

2019-03-27 13:20 UTC, MichielLeyman commented on backend/src/index.js
> +const express = require('express');
Not listed in dependencies in `package.json`

2019-03-27 13:41 UTC, archived-m reviewed
Great work.
Maybe it would be good to think about mailing in here already - and set up a password reset flow while we're on the topic of authentication.

If admins already have a way to get all users, why is there no way to update a user (set their role or `active` state) or delete them altogether?

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/graphql/resolvers/mutations.js
> +    // TODO Valid email format
Are you doing validation all at once in a separate PR?
Might be worth doing straight away

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/graphql/resolvers/queries.js
> +  users: async () => (users = await User.find()),
`users` is undefined. Did you want to return `User.find()`?

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/index.js
> +const express = require('express');
Not listed in dependencies in `package.json`

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/models/bankDetails.js
> +const bankDetailsSchema = new Schema(
Is a constructor, bot the variable and filename should be capitalized

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/models/user.js
> +const userSchema = new Schema({
Is a constructor, bot the variable and filename should be capitalized

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/models/address.js
> +const addressSchema = new Schema(
Is a constructor, bot the variable and filename should be capitalized

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/models/bankDetails.js
> +const bankDetailsSchema = new Schema(
So right now there's one payment method, being a bank account?

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/graphql/resolvers/queries.js
> +    if (!user || !rightPassword) {
Maybe `try` `catch` here, if it errors at any point, the email or password is incorrect.

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/index.js
> +    if (token) {
Can nest fewer ifs if we check for `!token` first and return a 401

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/graphql/resolvers/queries.js
> +  users: async () => (users = await User.find()),
Is this query for admins to get a listing of all users?

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/graphql/resolvers/mutations.js
> +  register: async (_, { user }) => {
Someone who freshly registers, can only create expenses right? If not, there needs to be an approve/reject mechanism

2019-03-27 13:41 UTC, MichielLeyman commented on backend/src/graphql/resolvers/mutations.js
> +    // Register && Return the user
TODO: send account confirmation email

2019-03-27 13:49 UTC, archived-m requested changes
Also, please add a basic README on which server environment variables are required for the app to start.

2019-04-08 08:18 UTC, auloin reviewed
> Also, please add a basic README on which server environment variables are required for the app to start.

I didn't see this one. I will make sure to add a .env.example file and explain all variables in the readme.

2019-04-08 08:18 UTC, auloin commented on backend/src/graphql/resolvers/queries.js
> +  users: async () => (users = await User.find()),
I'll add authorization later as well as roles

2019-04-08 08:18 UTC, auloin commented on backend/src/graphql/resolvers/queries.js
> +    if (!user || !rightPassword) {
There is no error handling yet, I'll add that later.

2019-04-08 08:18 UTC, auloin commented on backend/src/index.js
> +const express = require('express');
Yes there were a need to switch to apollo-server-express

2019-04-08 08:18 UTC, auloin commented on backend/src/index.js
> +    if (token) {
This mean anybody can register or login. I'm thinking of extract this logic in a separate function.

2019-04-08 08:18 UTC, auloin commented on backend/package.json
> +    "eslint-plugin-jsx-a11y": "^6.2.1",
Are react related plugins useful in the backend?

2019-04-08 08:22 UTC, auloin commented
What do you think of using directives for validation & authorization? A working example of directive here 
9d0dcaa.

2019-04-08 12:24 UTC, MichielLeyman commented on backend/package.json
> +    "eslint-plugin-jsx-a11y": "^6.2.1",
I think they're required for the airbnb style guide

2019-04-08 13:03 UTC, archived-m approved these changes

2019-04-08 13:03 UTC, merged